name: PyPI release
on: [push]

jobs:
  pypi_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.x
      uses: actions/setup-python@v6
      with:
        python-version: 3.x
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade setuptools wheel twine build
    - name: Build
      run: |
        python -m build 
        twine check dist/*
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
